steps:
  # Build the container image using BuildKit
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_NAME/sriyav-portfolio:$COMMIT_SHA'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'

# Push the built image to GCP Artifact Registry
images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_NAME/sriyav-portfolio:$COMMIT_SHA'

options:
  # Log directly to Google Cloud Logging to avoid dependencies on GCS log buckets
  logging: CLOUD_LOGGING_ONLY
